from typing import Protocol

from continuum_api.knowledge.types import IndexingStatus, RetrievedSnippet


class BlobStore(Protocol):
    def ensure_container(self, successor_id: str) -> str: ...
    def put(self, container: str, filename: str, data: bytes, content_type: str) -> str: ...
    def list_paths(self, container: str) -> list[str]: ...
    def read(self, container: str, blob_path: str) -> bytes: ...


class FoundryKnowledge(Protocol):
    def ensure_knowledge_base(self, name: str) -> str: ...
    def ensure_blob_source(self, kb: str, container: str) -> str: ...
    def start_indexing(self, kb: str) -> str: ...
    def indexing_status(self, run: str) -> IndexingStatus: ...
    def retrieve(self, kb: str, query: str, *, top: int = 5) -> list[RetrievedSnippet]: ...
